### ISSUE TITLE
Javascript errors after upgrading to v1.2.5

### ISSUE THREAD

**Issue by stephen-wagner** [greymass/anchor#1139]
![anchor-javascript-error](https://user-images.githubusercontent.com/17861657/123554392-6446aa00-d745-11eb-9aca-5649133306c7.PNG)

Receive this error fairly frequently after recent upgrade to v1.2.5

**Comment by aaroncox** [comment]
Sorry for the delayed response on this one - does it appear at any specific time or just randomly while the app is open?

**Comment by stephen-wagner** [comment]
It feels very random.

I reverted to 1.2.2 and don't get it.

**Comment by Xolem49** [comment]
I'm having the exact same issue.

But as you can see my DNS diag is on error.

Also i'm running a 1mb atrocious connection, maybe the websocket crashes constantly because of that.

What could i do? It's infuriating I have to relaunch the wallet 50 times a day.

Happens at random too.

I joined a winver for my OS version.

Thanks :)

![Capture](https://user-images.githubusercontent.com/16775670/124271821-3a72f600-db3e-11eb-89f7-49dfa7960374.JPG)
![Capture2](https://user-images.githubusercontent.com/16775670/124271823-3ba42300-db3e-11eb-9ad4-325ed219a7a2.JPG)
![winver](https://user-images.githubusercontent.com/16775670/124271828-3cd55000-db3e-11eb-90d8-0450a276a476.JPG)

**Comment by Xolem49** [comment]
> Sorry for the delayed response on this one - does it appear at any specific time or just randomly while the app is open?

Happens randomly to me too, can be minutes, can be hours. Sometimes it crashes when PC is idle, sometimes when i'm sending a lot of transactions, no patterns on this side.

**Comment by aaroncox** [comment]
Thanks for the additional details!

We pushed a release out today (https://github.com/greymass/anchor/releases/tag/v1.2.6) with some attempts at fixing this if you'd like to give it a shot. 

I'll leave this issue open to continue the discussion, since getting this resolved might take some more experimentation.

**Comment by Xolem49** [comment]
Installed. I'll report back how it went.

**Comment by Xolem49** [comment]
So i'm still having the error, the frequence seems lower but it persists

> Thanks for the additional details!
> 
> We pushed a release out today (https://github.com/greymass/anchor/releases/tag/v1.2.6) with some attempts at fixing this if you'd like to give it a shot.
> 
> I'll leave this issue open to continue the discussion, since getting this resolved might take some more experimentation.

So i'm still having the error, the frequence seems lower but it persists. The error is the exact same one.

**Comment by aaroncox** [comment]
Alright good to know, thanks for the follow up. We'll continue to dig until we can figure out why that WebSocket connection fails.

**Comment by bolelang** [comment]
> Thanks for the additional details!
> 
> We pushed a release out today (https://github.com/greymass/anchor/releases/tag/v1.2.6) with some attempts at fixing this if you'd like to give it a shot.
> 
> I'll leave this issue open to continue the discussion, since getting this resolved might take some more experimentation.

I upgraded from version 1.2.5 to 1.2.6 and I'm still experiencing this error.

**Comment by Xolem49** [comment]
> Alright good to know, thanks for the follow up. We'll continue to dig until we can figure out why that WebSocket connection fails.

The issue continues, I noticed when my connection was loading hard the issue happened almost instantly, because i'm running a 1MB internet.

So i dug further, and made a 4G bridge giving me 10 times more bandwidth and i ran with that for some hours without any crash.

So for me the websocket is closing randomly when the data is getting very low.

Any way to test that theory on your side? Simulate the absolute lowest possible connection as it will be the equivalent of mine.

Dunno if something can be done to avoid websocket closing on slow internet.. It makes the app unusable, because each time i launch a sign request after JS error, i have to crash the wallet, relaunch, reenter credentials and then the sign pop-up appears again without getting stuck mid process.

And it can crash up to 100 times a day as i'm very active on the network. Really a big issue for me.

Thanks.

**Comment by Xolem49** [comment]
Reverted back to 1.2.4 I couldn't stand it anymore.

I will keep updated if the issue is gone away by downgrading.

**Comment by Xolem49** [comment]
Back to 1.2.4 and the issue arised again, when it never happened on that version before.

I'm trying to uninstall and wipe any residual files before installing again, might be an update issue as well (I installed the new version without uninstalling the old one before)

I will come back with results.

**Comment by Xolem49** [comment]
For now, js error not showing.

But the signin requests still get stuck like when there was the error.

I opened devtools and these are showing when the wallet is stuck :

![Capture](https://user-images.githubusercontent.com/16775670/125013040-712f9b80-e06b-11eb-9da1-9a3d6984c6aa.JPG)

When restarting the wallet and with signin requests working normally I still get one error out of the 2 when it's frozen like so :

![Capture2](https://user-images.githubusercontent.com/16775670/125013164-a2a86700-e06b-11eb-9ae0-486733f783ba.JPG)

**Comment by aaroncox** [comment]
Thanks for the follow up. We'll try to simulate those issues with the websocket and we're working on ways to bypass the websocket completely in situations like this. That connection is a convenience helper, isn't required to actually sign, and definitely shouldn't be creating situations where it blocks the user from doing what they need to do.

The `/v1/resource_provider/request_transaction` that's giving the 400 response is expected and handled properly - it wouldn't be a part of what's causing the problems. The 410 response error in the screenshot is the culprit.

**Comment by Xolem49** [comment]
Thanks, looking forward to the next version.

In the meantime I reverted to 1.2.2 aswell and no more issues, i'll stay on that version while a fix gets cooked.

**Comment by ly6tAELNnOgUmC2bjWaiILuOdvTZuq5tJ** [comment]
I get this error too, randomly. Maybe it is the 22 wallets in there, the internet disconnects here and there or something else... And when this occurs, the confirm prompt for transaction won't pop up and it does not find accounts, so I have to select the authority account manually.

**Comment by aaroncox** [comment]
We just published a pre-release version we believe resolves these issues. I'd invite you to try it out and see if it resolves the issue for you:

https://github.com/greymass/anchor/releases/tag/v1.2.7

**Comment by ruizuikeda** [comment]
> We just published a pre-release version we believe resolves these issues. I'd invite you to try it out and see if it resolves the issue for you:
> 
> https://github.com/greymass/anchor/releases/tag/v1.2.7

v1.2.7 not work to me...

**Comment by aaroncox** [comment]
Could you describe what doesn't work? Is it that requests are not appearing after you log into an application?

**Comment by Xolem49** [comment]
"Is it that requests are not appearing after you log into an application?"

Exactly what seemed to happen. I Honestly didn't tested much, 1.2.2 is so flawless & so perfect for me, that anything not offering me that kind of user experience is immediately reverted back.

I just tried the 1.7.7, it got stuck constantly on most of my wax activities & I gave up in less than 2 minutes.

I really don't know what has been done since 1.2.2, but not a single version has been working correctly for me.

**Comment by aaroncox** [comment]
> I really don't know what has been done since 1.2.2, but not a single version has been working correctly for me.

We have been trying to figure out exactly what that change is, and why this issue is only happening for some users. Everything beyond 1.2.2 has worked flawlessly for a lot of other users but something is screwing it up for others such as yourself. 

Have you tried 1.2.3 as well? I specifically ask because if 1.2.3 is broken but 1.2.2 is working, that can help us further narrow down which change might be the cause of this. At this point we are just guessing and checking different configurations until we can reproduce the issue ourselves and track down what exactly is causing it. 

Thanks for the patience, I know I'm slowly losing mine when it comes to this issue and its my job 😅

**Comment by Xolem49** [comment]
1.2.4 was not working but i think i went directly to 1.2.2, skipping 1.2.3.

The issue could be in common with 1.2.3 too, i'm going to try but it's very costly for me to switch versions everytime, 2 hours job.

(30 minutes download, and if the programs is failing and i have to revert back it usually mess up the cache and I have to clear it before the old version works again.)

Then it takes 1 hour to my connection to reopen my working tabs ... That's why i'm not very colaborative for testing lol

I will try 1.2.3 but i won't be able to switch versions like that every other day.

**Comment by aaroncox** [comment]
I don't blame you one bit for not wanting to go through that process and wait that long! 😅 

Off topic - I've opened an issue (https://github.com/greymass/anchor/issues/1156) for us to investigate on how to potentially cut down the file size of the installer to ease that pain a bit. 

We will keep investigating in the mean time and hopefully find a way to recreate this situation and resolve it.

**Comment by Xolem49** [comment]
Well i still went through the process, cleared all cache, installed 1.1.7, no luck. It got stuck at the first signin transaction.

I uninstalled and cleared cache again, then proceeded to install 1.2.3 which seems to work just as well as 1.2.2

So to me, the issue started with 1.2.4 and all later versions.

I insist that my connection is garbage and the issue might not be reproductible under normal network.

(As an example I need to use 4G network to do a transfert with the native wax wallet, otherwise it gets rejected for some timeout..)

**Comment by aaroncox** [comment]
I am going to try to find some time to test using a 4G connection. I live in a pretty rural area with poor cellular connectivity and depend on my cable broadband for almost everything - so I am hoping that I'll be able to recreate the situation if I switch to relying on my 4G instead of broadband. 

Hopefully I'll find time to set this up and do some testing soon.

**Comment by includenull** [comment]
I get this every now and then too, randomly happens and is triggered by me going on and off of my VPN.

**Comment by benjiewheeler** [comment]
I'll share my experiences with this error. (I'm using v1.2.6)

It seems to occur a lot more frequently when my internet is worse than usual, after the error happens and the popup appears, signing requests don't open the signing window automatically (I have to click sign manually).

this behavior (not auto-opening the signing window) gets fixed if I quit anchor (CTRL+Q) and restart it, or if I reset my NIC (disable then re-enable it)

**Comment by aaroncox** [comment]
We managed to fix one major issue in 1.3.1 related to these disconnection errors. I'd welcome you all to upgrade and try that out - and see if the issue persists.

**Comment by Xolem49** [comment]
I'm currently trying 1.3.1, seems most issues in that thread have been resolved, except i'm having a new one now.

When trying to login to most anchor enabled websites, I just can't get the "Launch Anchor" button to work.

I tried to click every single pixel of it, no results.

I works if I copy paste the ESR link directly on the app, OR it also works if I right click on the button and open it in a new tab. This instantly triggers it, but staying on the same page the popup appears, and using the button to trigger it doesn't work anymore on any site I tried.

I tried to revert back to 1.2.3 that was working pretty well, and I now have that issue with that version too now ...

Lastest Windows 10 version, latest Chrome version (also tried with Firefox)

I checked if there was an entry in registry CLASSROOTS for esr:URL and there is, it's also linked to the correct anchor wallet.

Here are some screenshots : QR code removed on purpose and the link in registry shows "Anchor Wallet Portable" but it's the correct path as I used the NSIS version (x64). It doesn't works either using the non-portable version anyways.

![1](https://user-images.githubusercontent.com/16775670/140656876-ff25ff56-791f-4910-b1df-562cec1df3e4.JPG)
![2](https://user-images.githubusercontent.com/16775670/140656881-c776fb72-29ca-4c24-8d33-894ff592036c.JPG)
.
It's still usable like that but I just don't get why the button doesn't open ESR links anymore.

**Comment by aaroncox** [comment]
Any chance you have the Wombat wallet extension installed? 

We have gotten a few reports of this recently, where the Wombat wallet upgraded and it's now trying to handle those links. If that's the case, there's a setting within Wombat's extension to disable "Anchor Authentication" which will turn that off and allow Anchor to function again if you refresh the page.

**Comment by Xolem49** [comment]
My god, it was it.

I uninstalled this wallet completely, as it was the thing that literally made my wax/tron/hive keychain wallet unusable.

An app that does this get's instant blacklisted for me. Unacceptable Wombat, what a shame.

**Comment by Xolem49** [comment]
And thanks Aaron, i was literally going crazy.

**Comment by aaroncox** [comment]
No problem! 

I'm going to close out this issue since it's been open a while and diverged topics a couple times. If anyone else runs into issues with anything, feel free to open a new one.
